version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    open-pull-requests-limit: 10
    reviewers:
      - "Jeffa2002"
    labels:
      - "dependencies"
    groups:
      next-ecosystem:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Perth"
    labels:
      - "dependencies"
