import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crossbench — Your voice in parliament",
  description: "Vote on Australian federal legislation. Make your MP listen.",
  metadataBase: new URL("https://crossbench.io"),
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Read nonce generated by middleware — applied to any inline scripts Next.js injects
  const nonce = (await headers()).get('x-nonce') ?? undefined

  return (
    <html lang="en">
      <head>
        {/* CSP nonce meta tag — consumed by Next.js for its inline script chunks */}
        {nonce && <meta property="csp-nonce" content={nonce} />}
      </head>
      <body className={inter.className} style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
