import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { headers } from "next/headers";
import Footer from "@/components/Footer";
import FirstPartyAnalyticsTracker from "@/components/FirstPartyAnalyticsTracker";
import PlausibleTracker from "@/components/PlausibleTracker";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crossbench — Verified constituent sentiment on federal bills",
  description: "Vote on current Australian federal bills and see the verified electorate signal MPs can read in aggregate.",
  metadataBase: new URL("https://crossbench.io"),
  openGraph: {
    title: "Crossbench",
    description: "Verified constituent sentiment on Australian federal bills, shown safely in aggregate by electorate.",
    url: "https://crossbench.io",
    siteName: "Crossbench",
    images: [{ url: "/mp-dashboard-mock.png", width: 1200, height: 800, alt: "Crossbench MP electorate dashboard" }],
    locale: "en_AU",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Crossbench",
    description: "Verified constituent sentiment on Australian federal bills, shown safely in aggregate by electorate.",
    images: ["/mp-dashboard-mock.png"],
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Read nonce generated by middleware — applied to any inline scripts Next.js injects
  const nonce = (await headers()).get('x-nonce') ?? undefined

  return (
    <html lang="en">
      <head>
        {/* CSP nonce meta tag — consumed by Next.js for its inline script chunks */}
        {nonce && <meta property="csp-nonce" content={nonce} />}
      </head>
      <body className={inter.className} style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        {children}
        <Footer />
        <PlausibleTracker />
        <Suspense fallback={null}>
          <FirstPartyAnalyticsTracker />
        </Suspense>
      </body>
    </html>
  )
}
